version: "3"

services:
    crawler:
        build:
          context: .
          dockerfile: Dockerfile_crawler
        tty: true
        image: crawler-screen
        container_name: crawler-screen
        volumes:
            - ./firmwares:/crawler/firmwares