DLINK = "https://support.dlink.com"
TPLINK_EN = "https://www.tp-link.com"
INTELBRAS = "https://www.intelbras.com/pt-br/ajuda-download/download/"
NETGEAR = "https://www.netgear.com"
TENDA_EN = ""
TRENDNET = "https://www.trendnet.com"